global:
  scrape_interval: 30s 
  evaluation_interval: 30s
scrape_configs:
- job_name: cadvisor
  scrape_interval: 15s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: pythonapp
  scrape_interval: 15s
  static_configs:
  - targets:
    - app:8000
- job_name: pythonwebapp
  scrape_interval: 15s
  static_configs:
  - targets:
    - app-web:6500